apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubevela

helmCharts:
- name: vela-core
  includeCRDs: true
  namespace: kubevela
  releaseName: vela-core
  version: 1.4.8
  repo: https://charts.kubevela.net/core

resources:
- namespace.yaml