apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/Simon-Boyer/homeserver'
    targetRevision: main
    path: namespaces/argocd
  syncPolicy:
    automated:
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-mesh-source
spec:
  project: default
  destination:
    namespace: public
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/Simon-Boyer/homeserver'
    targetRevision: main
    path: namespaces/traefik-mesh
  syncPolicy:
    automated:
      selfHeal: true