apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/Simon-Boyer/homeserver-config'
    targetRevision: main
    path: namespaces/argocd
  syncPolicy:
    automated:
      selfHeal: true