apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: public
  namespace: argocd
spec:
  sourceRepos:
  - 'https://github.com/Simon-Boyer/homeserver-config'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'