apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: public
spec:
  sourceRepos:
  - 'https://github.com/Simon-Boyer/homeserver'
  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'