apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: nextcloud/nextcloud
  includeCRDs: false
  valuesInline:
    persistence:
      enabled: true
  releaseName: nextcloud
  version: 3.0.3
  repo: https://nextcloud.github.io/helm/