apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
  - namespace.yaml
  - simon-nextcloud-secret.json
  - ingress.yaml

helmCharts:
- name: nextcloud
  includeCRDs: false
  valuesInline:
    image:
      flavor: fpm-alpine
    persistence:
      enabled: true
      storageClass: linode-block-storage-retain
      size: 20Gi
    nextcloud:
      host: cloud.codegameeat.com
      existingSecret:
        enabled: true
        secretName: simon-nextcloud-secret
        usernameKey: user
        passwordKey: password
    nginx:
      enabled: true
    redis:
      enabled: true
    metrics:
      enabled: true
  releaseName: nextcloud
  version: 3.0.3
  repo: https://nextcloud.github.io/helm