apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: sealed-secrets
  includeCRDs: true
  valuesInline:
    persistence:
      enabled: true
  releaseName: sealed-secrets
  version: 1.0.11
  repo: https://charts.bitnami.com/bitnami