apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/Simon-Boyer/homeserver'
    targetRevision: japan-cluster
    path: mgmt-cluster/argocd
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashy
spec:
  project: default
  destination:
    namespace: dashy
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/Simon-Boyer/homeserver'
    targetRevision: japan-cluster
    path: namespaces/dashy
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  project: default
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/Simon-Boyer/homeserver'
    targetRevision: japan-cluster
    path: mgmt-cluster/sealed-secrets
  syncPolicy:
    automated:
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-mesh
spec:
  project: default
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/Simon-Boyer/homeserver'
    targetRevision: japan-cluster
    path: namespaces/traefik-mesh
  syncPolicy:
    automated:
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  project: default
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/Simon-Boyer/homeserver'
    targetRevision: japan-cluster
    path: mgmt-cluster/traefik
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevious
spec:
  project: default
  destination:
    namespace: kubevious
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/Simon-Boyer/homeserver'
    targetRevision: japan-cluster
    path: mgmt-cluster/kubevious
  syncPolicy:
    automated:
      selfHeal: true
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: kubevela
# spec:
#   project: default
#   destination:
#     namespace: kubevela
#     server: https://kubernetes.default.svc
#   source:
#     repoURL: 'https://github.com/Simon-Boyer/homeserver'
#     targetRevision: japan-cluster
#     path: mgmt-cluster/kubevela
#   syncPolicy:
#     automated:
#       selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
spec:
  project: default
  destination:
    namespace: nextcloud
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/Simon-Boyer/homeserver'
    targetRevision: japan-cluster
    path: namespaces/nextcloud
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hugo
spec:
  project: default
  destination:
    namespace: hugo
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/Simon-Boyer/simons-travel-blog'
    targetRevision: main
    path: .
  syncPolicy:
    automated:
      selfHeal: true
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: paperlessng
# spec:
#   project: default
#   destination:
#     namespace: paperlessng
#     server: https://kubernetes.default.svc
#   source:
#     repoURL: 'https://github.com/Simon-Boyer/homeserver'
#     targetRevision: japan-cluster
#     path: namespaces/paperlessng
#   syncPolicy:
#     automated:
#       selfHeal: true