apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

replacements:
- path: ../../base/route-replacement.yaml
- path: ../../base/ingress-service-replacement.yaml

resources:
- deployment.yaml

## MODIFY BELOW ##
## ↓ ↓ ↓ ↓ ↓ ↓  ##

namespace: cinny-app
namePrefix: cinny-
commonLabels:
  app.kubernetes.io/name: cinny

commonAnnotations:
    route: Host(`cinny.codegameeat.com`)