apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cinny-app
namePrefix: cinny-
commonLabels:
  app.kubernetes.io/name: cinny

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml