apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api
  namespace: traefik
spec:
  encryptedData:
    apikey: AgDYoOBez3AjHC0Y+Bm5TssdjzGyu9cXZO4+TI6LBpHwUeZh28KTxR1jFUcL7rWQHOpwyaZTwIUMFPBhEWnhXUg8InR94PTV1Xj9J2YZpmSBMBOeqMmRBP//6d6BSouGeddFu3tg7xgqQ84GeJy9PG0xw9LQ3vUcn89n+W//VX/8S8eMn76EOZ3YAtUMBEQlkdmuawfe7TiQixaj55Sdjshh5if1iD9XBjf+F7uqc5lFb4PvlpXPEqw1tM/h7l8YoY7enRTbS/HNtWwCaokml1jiDMm6H+WBhaY5gI1uPakzI6oQZ6UWmboc+9UeR01JmfC3xTDA7AHcMng7FAjYOsun6AA6pf8fDROw62unMMyP0HaJkWNT/T7+IgqF9w3YRRtImVeYObyOx7Sap3TvNf/oX1u5EUVCjRg1qGniM2V1XgKa+lf9gIZSbnVo6qaBngig/6hFYpPcYQdBC/SU47iJX/dALJC9JCw2OQRrHv056IwZDeDsJhe2muBa+O++SuimCVOtu0uWNmvIWU2QwtYTc0m4KNgOi7YK9oKBUnN5qQuPCZYXRPsFXdvsYn5V6bRhmkpmO5Ai+kub+KsBIyun4tt