---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: traefik
spec:
  project: public
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 10.19.5
    helm:
      releaseName: traefik
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik