apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  project: default
  destination:
    namespace: public
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/metallb/metallb-operator.git'
    targetRevision: v0.12.0
    path: bin/metallb-operator.yaml
  syncPolicy:
    automated:
      selfHeal: true
---
apiVersion: metallb.io/v1beta1
kind: AddressPool
metadata:
  name: addresspool-main
  namespace: metallb-system
spec:
  protocol: layer2
  addresses:
    - 10.10.2.100-10.10.2.255