---



k3s_cluster:
  hosts:
    kube-0:
      ansible_host: kube-0
      ip: 10.10.1.2
      ansible_python_interpreter: /usr/bin/python3
      image_link: https://dietpi.com/downloads/images/DietPi_OdroidN2-ARMv8-Bullseye.7z
    kube-1:
      ansible_host: kube-1
      ip: 10.10.1.3
      ansible_python_interpreter: /usr/bin/python3
      image_link: https://dietpi.com/downloads/images/DietPi_OdroidXU4-ARMv7-Bullseye.7z
    kube-2:
      ansible_host: kube-2
      ip: 10.10.1.4
      ansible_python_interpreter: /usr/bin/python3
      image_link: https://dietpi.com/downloads/images/DietPi_RPi-ARMv8-Bullseye.7z