---

- name: Build a cluster with a single control node
  hosts: k3s_cluster
  vars:
    k3s_become: true
  roles:
    - role: xanmanning.k3s

- name: Install Sidero
  hosts: k3s_cluster
  environment:
    SIDERO_CONTROLLER_MANAGER_HOST_NETWORK: "true"
    SIDERO_CONTROLLER_MANAGER_API_ENDPOINT: "{{ hostvars[ groups['k3s_cluster'][0] ].ansible_host }}"
    SIDERO_CONTROLLER_MANAGER_SIDEROLINK_ENDPOINT: "{{ hostvars[ groups['k3s_cluster'][0] ].ansible_host }}"
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  tasks:
    - ansible.builtin.command: "curl -L {{ clusterctl_release }} -o clusterctl"
    - ansible.builtin.command: chmod +x clusterctl
    - ansible.builtin.command: ./clusterctl init -b talos -c talos -i sidero

- name: Send kubeconfig
  hosts: k3s_cluster
  tasks:
    - ansible.builtin.shell: sed 's/127.0.0.1/{{ hostvars[ groups['k3s_cluster'][0] ].ansible_host }}/g' /etc/rancher/k3s/k3s.yaml | nc {{ computer_manager_ip }} 1605
