apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: collector
  namespace: observability
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:55690
      jaeger:
        protocols:
          thrift_http:
    processors:
      batch:
        timeout: 30s
        send_batch_size: 100

    exporters:
      tempo:
        endpoint: tempo.observability.traefik.mesh:3100

    service:
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          processors: [batch]
          exporters: [tempo]