---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cortex
  namespace: argocd
spec:
  project: public
  source:
    chart: cortex
    repoURL: https://cortexproject.github.io/cortex-helm-chart
    targetRevision: 1.5.1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability