---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: public
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.6.4
    helm:
      releaseName: loki
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability