---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: public
  source:
    chart: tempo
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.15.3
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability