---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: public
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 35.4.2
    helm:
      valueFiles:
        - prometheus-values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability