---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: public
  source:
    chart: tempo
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.15.3
    helm:
      values: |
        fullnameOverride: tempo
        gateway:
          enabled: true                               # To enable gateway
        traces:                                       # To enable ports for different tracing formats
          jaeger:                                     # Enabling port for jaeger HTTP endpoint of Tempo
            thriftHttp: true
          otlp:
            http: true                                # Enabling port for openTelemetry HTTP endpoint of Tempo
            grpc: true                                # Enabling port for openTelemetry gRPC endpoint of Tempo
        search:
          enabled:
            true                                      # To enable tempo search option when viewing traces in Grafana
  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability