---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik-mesh
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-mesh
  namespace: traefik-mesh
spec:
  project: public
  source:
    chart: traefik-mesh
    repoURL: https://helm.traefik.io/mesh
    targetRevision: 4.0.2
    helm:
      releaseName: traefik-mesh
      values: |
        tracing:
          deploy: true
          jaeger:
            enabled: true
        metrics:
          deploy: true
          prometheus:
            # whether to expose Prometheus metrics
            enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik-mesh