---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik-mesh
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-mesh
  namespace: argocd
spec:
  project: public
  source:
    chart: traefik-mesh
    repoURL: https://helm.traefik.io/mesh
    targetRevision: 4.0.2
    helm:
      releaseName: traefik-mesh
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik-mesh