apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: harvester-secret
spec:
  encryptedData:
    token: AgAdJRZzwoJUmj7BUVWlCPF5H7aENS0wq/hBt3E/5zpVqNFVeyVDjek2e47Zs8bGFhSKRo2WrnGSNINYdWxesSdmMQkkl5Rt/BgAXLfVvNRjlARCbo+Va37su03mnhOnESB+1XBtX6ie6FYpD0g45ckA1I2/vl6LbmPUDlV6SoMsnSjxJf5hKtslcOP5XoJ0WQYV0HRDRGybhk7YJPdNTVwaG1vhdB84Uik2l1L/9VRG2cZbUamC/Q9dpfb9DxH57CQUOZLFceUyTAdt1n9x3IjgyTLgs9eWVcNOzcZyut0GlNtezAMSBpEkfK9beOGRGVHtojQYev7eoBuYxtb4d+nRzu88sQlng/+qRHOvI7YsSb+HslQSTmKMG9IG9sb3bFnbYy2/HJCXqfoaS+/rQJI0wl1x70ZJ/GogAHF0WYn5CdWJ3omXw3Bmlb36l4tR06ioALcTXrspgVJWRjyIMRpOEC3hvaUgNWBM+4lAfcAl/fxljEXx8SdxzNdHgKQnjaS8+t35QBz1N0V7po5YHagZ4aIcP8Mmwyb/9XsOaQ9P0yOz5Apw3bptpuMDFcmeksqLJxkuxCcz05dNpkQvfDj+hb+r1KZ4f+7e+Q13zQPQo8AEb+vWeuR/rzAylti9fUVc1vQnZcf9bvIJcZHJumIn/adVf2zUzfkjHiLXF+2xbtAt0naIiCS2f1v/K7cslAXo+0I=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: harvester-secret

